AWSTemplateFormatVersion: '2010-09-09'
Description: An application to periodically search tweets and store them in DynamoDB.
Resources:
  TweetsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: TweetId
          AttributeType: S
        - AttributeName: QueryId
          AttributeType: S
      KeySchema:
        - AttributeName: QueryId
          KeyType: HASH
        - AttributeName: TweetId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  QueriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: QueryId
          AttributeType: S
      KeySchema:
        - AttributeName: QueryId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  TwitterSearchAndStoreHandler:
    Properties:
      CodeUri: ./bundle.zip
      Handler: src.twitter_handler.search_and_store
      Runtime: python3.6
      Timeout: 60
    Type: AWS::Serverless::Function


Transform: AWS::Serverless-2016-10-31